[package]
name = "abi-converter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "abi-converter"
path = "script.rs"

[dependencies]
serde_json = "1.0"
clap = { version = "4.0", features = ["derive"] }
glob = "0.3"
